spring:
  jpa:
    generate-ddl: true
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/soaproject
    username: soaproject
    password: easypassword
    driver-class-name: org.postgresql.Driver
server:
  port: 8082